### ISSUE TITLE
cuisine.file_write fails with 7.6 and 7.7

### ISSUE THREAD

**Issue by agabert** [sebastien/cuisine#185] opened 2015-06-14 01:20 UTC
subject says it all.

**Comment by sebastien** [comment] 2015-06-14 13:09
I would need more info to help you. What is the error, which system are you on? Thanks

**Comment by sebastien** [comment] 2015-06-15 15:10
OK, I found the reason, it was a regression in md5/sha1 sum functions. It should be fixed in 7.8

**Closed** 2015-07-08 13:53 UTC
